services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: images
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio
    command: ["server", "/data", "--console-address", ":9001"]
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      mc mb myminio/${MINIO_BUCKET};
      mc anonymous set public myminio/${MINIO_BUCKET};
      exit 0;"

  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - minio
    restart: always

  worker:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - kafka
      - minio
    command: ["./worker-app"]
    restart: always